title: "Murder at Blackwood Manor"
victim: "Sir Reginald Blackwood"
time_of_death: "Between 9:00 PM and 11:00 PM"
location: "Blackwood Manor library"
weapon: "Ornamental dagger from the collection"
clues:
  holmes_clues: |
    - Footprints in the garden soil show size 10 men's shoes with a distinctive worn heel pattern
    - Traces of tobacco ash near the body - a rare blend from the Orient
    - The victim's watch was stopped at 10:22, likely broken during a struggle
  poirot_clues: |
    - The victim received a mysterious letter earlier that day (now missing)
    - The housekeeper reports hearing raised voices at 9:45 PM
    - The will was recently changed to favor the nephew over the wife
  marple_clues: |
    - The garden flowers were trampled near the kitchen entrance
    - Cook mentions the nephew was unusually interested in the dinner arrangements
    - The victim's sister-in-law visited unexpectedly that afternoon
suspects:
  - "Lady Eleanor Blackwood (wife)"
  - "Jonathan Blackwood (nephew)"
  - "Dr. William Graves (family physician)"
  - "Mrs. Agatha Pierce (sister-in-law)"